# contents
nav:
  - Home:
      - インデックス: index.md
      - ほげ: hoge.md

# metadata
site_name: MkDocs Test Site
docs_dir: src
use_directory_urls: false

# theme
theme:
  name: material
  language: ja

# extension
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
